import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

type ContractInputs = {
  mode: string;
  publicInputsForContract: string[];
  proofBytes: string;
};

const SOURCE = "pactra-public-inputs.json";
const DEST = "contracts/groth16-verifier/src/test_vector.rs";
const PACTRA_DEST = "contracts/pactra/src/fixtures/valid_groth16_proof.rs";
const PUBLIC_INPUT_NAMES = [
  "policy_commitment",
  "vendor_hash",
  "amount",
  "invoice_commitment",
  "nullifier",
  "mandate_id_hash"
];

function bytesFromHex(hex: string, expectedLength: number): number[] {
  const normalized = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (normalized.length !== expectedLength * 2) {
    throw new Error(`Expected ${expectedLength} bytes, got ${normalized.length / 2}`);
  }

  return normalized.match(/.{2}/g)?.map((byte) => Number.parseInt(byte, 16)) ?? [];
}

function rustByteArray(bytes: number[], indent: string): string {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    lines.push(`${indent}${bytes.slice(i, i + 16).map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
  }
  return lines.join("\n");
}

function rustNamedByteConstant(name: string, bytes: number[]): string {
  return `pub const ${name}: [u8; 32] = [\n${rustByteArray(bytes, "    ")}\n];`;
}

function bigIntFromBytes(bytes: number[]): bigint {
  return BigInt(`0x${bytes.map((byte) => byte.toString(16).padStart(2, "0")).join("")}`);
}

const bundle = JSON.parse(readFileSync(SOURCE, "utf8")) as ContractInputs;
if (bundle.mode !== "groth16") {
  throw new Error(`${SOURCE} does not contain a Groth16 proof bundle.`);
}
if (bundle.publicInputsForContract.length !== 6) {
  throw new Error("Expected six public inputs for mandate.circom.");
}

const proof = bytesFromHex(bundle.proofBytes, 256);
const publicInputs = bundle.publicInputsForContract.map((input) => bytesFromHex(input, 32));
const amount = bigIntFromBytes(publicInputs[2]);

const content = `// @generated by \`npm run verifier:test-vector\`.
// Source: ${SOURCE}
// Regenerate after changing the circuit, proving key, or sample circuit input.

pub const VALID_PROOF: [u8; 256] = [
${rustByteArray(proof, "    ")}
];

pub const VALID_PUBLIC_INPUTS: [[u8; 32]; 6] = [
${publicInputs.map((input) => `    [\n${rustByteArray(input, "        ")}\n    ],`).join("\n")}
];
`;

writeFileSync(DEST, content);
console.log(`Wrote ${DEST}`);

const pactraContent = `// @generated by \`npm run verifier:test-vector\`.
// Source: ${SOURCE}
// Regenerate after changing the circuit, proving key, or sample circuit input.
#![allow(dead_code)]

pub const PROOF: [u8; 256] = [
${rustByteArray(proof, "    ")}
];

pub const PUBLIC_INPUTS: [[u8; 32]; 6] = [
${publicInputs.map((input) => `    [\n${rustByteArray(input, "        ")}\n    ],`).join("\n")}
];

pub const PUBLIC_INPUT_ORDER: [&str; 6] = [
${PUBLIC_INPUT_NAMES.map((name) => `    "${name}",`).join("\n")}
];

pub const AMOUNT: i128 = ${amount.toString()};

${rustNamedByteConstant("MANDATE_ID", Array.from({ length: 32 }, (_, index) => index + 1))}
${rustNamedByteConstant("POLICY_COMMITMENT", publicInputs[0])}
${rustNamedByteConstant("VENDOR_HASH", publicInputs[1])}
${rustNamedByteConstant("AMOUNT_INPUT", publicInputs[2])}
${rustNamedByteConstant("INVOICE_COMMITMENT", publicInputs[3])}
${rustNamedByteConstant("NULLIFIER", publicInputs[4])}
${rustNamedByteConstant("MANDATE_ID_HASH", publicInputs[5])}
`;

mkdirSync(dirname(PACTRA_DEST), { recursive: true });
writeFileSync(PACTRA_DEST, pactraContent);
console.log(`Wrote ${PACTRA_DEST}`);
