import { readFileSync, writeFileSync } from "node:fs";
import { VKEY, assertFile } from "./tooling.js";

type G1 = [string, string, string];
type G2 = [[string, string], [string, string], [string, string]];

type VerificationKey = {
  protocol: string;
  curve: string;
  nPublic: number;
  vk_alpha_1: G1;
  vk_beta_2: G2;
  vk_gamma_2: G2;
  vk_delta_2: G2;
  IC: G1[];
};

assertFile(VKEY, "Run npm run circuit:setup first to create verification_key.json.");

const key = JSON.parse(readFileSync(VKEY, "utf8")) as VerificationKey;
if (key.protocol !== "groth16") {
  throw new Error(`Expected groth16 verification key, got ${key.protocol}`);
}

if (!["bn128", "bn254"].includes(key.curve)) {
  throw new Error(`Expected BN254/bn128 curve, got ${key.curve}`);
}

if (key.IC.length !== key.nPublic + 1) {
  throw new Error(`Expected IC length ${key.nPublic + 1}, got ${key.IC.length}`);
}

const rust = `// @generated by \`npm run verifier:export\`.
// Source: ${VKEY}
// Do not edit by hand. Regenerate after changing circuits/mandate.circom or the proving setup.

pub const GENERATED: bool = true;
pub const N_PUBLIC: usize = ${key.nPublic};
pub const IC_LEN: usize = ${key.IC.length};

pub const ALPHA_1: [u8; 64] = ${rustArray(g1Bytes(key.vk_alpha_1))};
pub const BETA_2: [u8; 128] = ${rustArray(g2Bytes(key.vk_beta_2))};
pub const GAMMA_2: [u8; 128] = ${rustArray(g2Bytes(key.vk_gamma_2))};
pub const DELTA_2: [u8; 128] = ${rustArray(g2Bytes(key.vk_delta_2))};
pub const IC: [[u8; 64]; IC_LEN] = [
${key.IC.map((point) => `    ${rustArray(g1Bytes(point))},`).join("\n")}
];
`;

writeFileSync("contracts/groth16-verifier/src/verifying_key.rs", rust);
console.log("Wrote contracts/groth16-verifier/src/verifying_key.rs");
console.log("Run cargo test --workspace to compile the exported verifier constants.");

function g1Bytes(point: G1): number[] {
  return [...fieldBytes(point[0]), ...fieldBytes(point[1])];
}

function g2Bytes(point: G2): number[] {
  const [x, y] = point;
  return [
    ...fieldBytes(x[1]),
    ...fieldBytes(x[0]),
    ...fieldBytes(y[1]),
    ...fieldBytes(y[0])
  ];
}

function fieldBytes(value: string): number[] {
  const hex = BigInt(value).toString(16).padStart(64, "0");
  return Array.from(Buffer.from(hex, "hex"));
}

function rustArray(bytes: number[]): string {
  return `[${bytes.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")}]`;
}
